# Generated by Django 4.2.16 on 2024-12-11 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeroom_number', models.CharField(max_length=5, unique=True)),
                ('class_year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophmore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=15)),
                ('photo_permission', models.BooleanField(default=False)),
                ('profile_type', models.IntegerField(choices=[(0, 'Student'), (1, 'Teacher')], default=0)),
                ('homeroom_number', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='users.homeroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
