# Generated by Django 4.2.16 on 2024-12-19 20:06

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0008_beneficiary_featured_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=15, unique=True)),
                ('profile_pic', cloudinary.models.CloudinaryField(default='default-profile-pic.jpg', max_length=255, verbose_name='image')),
                ('profile_type', models.IntegerField(choices=[(0, 'Student'), (1, 'Teacher'), (2, 'School Admin')], default=0)),
                ('homeroom', models.ForeignKey(default='999', on_delete=django.db.models.deletion.SET_DEFAULT, to='volunteer.homeroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['homeroom', 'user'],
            },
        ),
    ]
