# Generated by Django 4.2.16 on 2025-01-08 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_remove_classroom_id_alter_classroom_classroom_number'),
        ('users', '0002_alter_profile_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classroom',
            field=models.ForeignKey(default='999', on_delete=django.db.models.deletion.SET_DEFAULT, to='volunteer.classroom'),
        ),
    ]
