# Generated by Django 4.2.16 on 2025-01-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='completed',
            field=models.SmallIntegerField(choices=[(0, 'Completed'), (1, 'Incomplete')], default=1),
        ),
    ]
