# Generated by Django 4.2.16 on 2025-01-05 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='', max_length=200)),
                ('task_location', models.CharField(default='TBD (use pseudonym for private beneficiary)', max_length=200)),
                ('dates', models.CharField(default='to be determined', max_length=200)),
                ('times', models.CharField(default='to be determined', max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('credit_minutes_requested', models.SmallIntegerField(default=0)),
                ('credit_minutes_approved', models.SmallIntegerField(default=0)),
                ('teacher_approved', models.BooleanField(default=False)),
                ('publish_ok', models.BooleanField(default=False)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='volunteer.beneficiary')),
                ('reserved_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
