# Generated by Django 4.2.16 on 2025-01-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_alter_slot_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='completed',
            field=models.SmallIntegerField(choices=[(0, 'Incomplete'), (1, 'Completed')], default=1),
        ),
    ]
