# Generated by Django 4.2.16 on 2024-12-14 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
    ]
