# Generated by Django 4.2.16 on 2025-01-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='task_location',
            field=models.CharField(default='use pseudonym for private beneficiary)', max_length=200),
        ),
    ]
