# Generated by Django 4.2.16 on 2025-01-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_alter_slot_task_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='teacher_approved',
        ),
    ]
