# Generated by Django 4.2.16 on 2024-12-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_alter_slot_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
