# Generated by Django 4.2.16 on 2025-01-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_remove_slot_teacher_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='completed',
            field=models.BooleanField(blank=True),
        ),
    ]
