# Generated by Django 4.2.16 on 2025-01-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_alter_beneficiary_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='short_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='slot',
            name='task_location',
            field=models.CharField(default='use pseudonym                                     for private beneficiary)', max_length=200),
        ),
    ]
