# Generated by Django 4.2.16 on 2025-01-17 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_alter_beneficiary_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='task_location',
            field=models.CharField(default='use pseudonymfor private beneficiary)', max_length=200),
        ),
    ]
