# Generated by Django 4.2.16 on 2025-01-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_alter_slot_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='completed',
            field=models.CharField(choices=[('Yes', 'Completed'), ('No', 'Incomplete')], default='No'),
        ),
    ]
