# Generated by Django 4.2.16 on 2024-12-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_homeroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='short_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
