# Generated by Django 4.2.16 on 2024-12-18 23:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_beneficiary_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='hearts.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='credit_minutes_requested',
            field=models.SmallIntegerField(default=0),
        ),
    ]
