# Generated by Django 4.2.16 on 2025-01-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_alter_slot_task_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='task_location',
            field=models.CharField(default='(use pseudonym for private beneficiary)', max_length=200),
        ),
    ]
