# Generated by Django 4.2.16 on 2024-12-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_beneficiary_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='credit_minutes_approved',
            field=models.SmallIntegerField(default=0),
        ),
    ]
