# Generated by Django 4.2.16 on 2025-01-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0008_alter_slot_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='id',
        ),
        migrations.AlterField(
            model_name='classroom',
            name='classroom_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
