# Generated by Django 4.2.16 on 2024-12-27 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0009_slot_credit_minutes_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='slug',
        ),
    ]
