# Generated by Django 4.2.16 on 2024-12-28 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0010_remove_slot_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ['beneficiary_name']},
        ),
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['created_on']},
        ),
    ]
