# Generated by Django 4.2.16 on 2024-12-28 06:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_collaboraterequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='about_default.jpg', max_length=255, verbose_name='image'),
        ),
    ]
